# -------
# Library
# -------

library:
  name: KotPreferences
  api: 21
  github: MFlisar/KotPreferences
  maven: io.github.mflisar.kotpreferences
  maven-main-library: core
  multiplatform: true
  platforms:
    - jvm
    - android
    - macos
    - ios
  screenshots:  []
  branch: master
  demo: true

# ------------
# Dependencies
# ------------

dependencies:
  compose-multiplatform: 1.7.3 # https://github.com/JetBrains/compose-multiplatform/releases
  jetpack-compose-runtime: 1.7.6 # https://developer.android.com/jetpack/androidx/releases/compose-runtime
  jetpack-compose-material3: 1.3.1 # https://developer.android.com/jetpack/androidx/releases/compose-material3
  experimental: false

# ------------
# Groups
# ------------

groups:
  - name: core
    label: Core
    gradle-comment: core
  - name: storage
    label: Storage
    gradle-comment: select a storage implementation
  - name: extensions
    label: Extensions
    gradle-comment: optional extensions
  - name: encryptions
    label: Encryption
    gradle-comment: optionally add additional encryption

# ------------
# Modules
# ------------

modules:
  - name: core
    group: core
    description: provides delegate based preferences
    optional: false
    platforms:
      - jvm
      - android
      - macos
      - ios
    platforms-info: ""
    dependencies: []
  - name: encryption-aes
    group: encryptions
    description: provides AES based encryption
    optional: true
    platforms:
      - android
    platforms-info: (1)
    dependencies: []
  - name: extension-compose
    group: extensions
    description: provides composable extensions
    optional: true
    platforms:
      - jvm
      - android
      - macos
      - ios
    platforms-info: ""
    dependencies: []
  - name: storage-datastore
    group: storage
    description: provides a storage implementation based on jetpack datastore
    optional: true
    platforms:
      - jvm
      - android
      - macos
      - ios
    platforms-info: ""
    dependencies: []
  - name: storage-keyvalue
    group: storage
    description: provides a storage implementation based on a simple key-value text file
    optional: true
    platforms:
      - jvm
      - android
      - macos
      - ios
    platforms-info: ""
    dependencies: []