[versions]

# mflisar (local snapshot: "LOCAL-SNAPSHOT")
kmpdevtools =               "7.1.8" # change via "updateDevToolsVersion" gradle task!

[plugins]

# mflisar
kmpdevtools-buildplugin =               { id = "io.github.mflisar.kmpdevtools.plugins-build-gradle",    version.ref = "kmpdevtools" }

[libraries]

# mflisar
# --